# Generated by Django 5.0.4 on 2024-07-06 19:49

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Investigador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('rol', models.CharField(choices=[('administrador', 'administrador'), ('vicedecano', 'vicedecano'), ('vicerrector', 'vicerrector'), ('investigador', 'investigador')], default='Investigador', max_length=20, verbose_name='Rol de Usuario')),
                ('categoria_cientifica', models.CharField(choices=[('Investigador Agregado', 'Investigador Agregado'), ('Investigador Auxiliar', 'Investigador Auxiliar'), ('Investigador Titular', 'Investigador Titular')], max_length=22, verbose_name='Categoría Científica')),
                ('categoria_docente', models.CharField(choices=[('Licenciado', 'Licenciado'), ('Maestria', 'Maestria'), ('Doctorado', 'Doctorado')], max_length=20, verbose_name='Categoría Docente')),
                ('area', models.CharField(max_length=100)),
                ('perfil_google', models.URLField(blank=True, null=True)),
                ('perfil_researchgate', models.URLField(blank=True, null=True)),
                ('orci', models.CharField(max_length=10, unique=True)),
                ('ci', models.CharField(max_length=11, unique=True)),
                ('facultad', models.CharField(choices=[('Facultad de Ciencias Sociales', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PubliUnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('editorial', models.CharField(default='Editorial...', max_length=200)),
                ('capitulo', models.CharField(max_length=9, null=True)),
                ('volumen', models.CharField(max_length=9, null=True)),
                ('fecha_creacion', models.DateField()),
                ('categoriaCientifica', models.CharField(choices=[('Funcionando', 'Funcionando'), ('Roto', 'Roto'), ('Baja', 'Baja'), ('Definir', 'Definir')], default='Seleccione...', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('facultad', models.CharField(choices=[('Facultad de Ciencias Sociales', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50)),
                ('departamento', models.CharField(choices=[('CECID', 'CECID'), ('CEGEDEL', 'CEGEDEL'), ('CENFOLAB', 'CENFOLAB'), ('AFITCOMB', 'AFITCOMB'), ('CEGO', 'CEGO'), ('CECE', 'CECE'), ('CEAR', 'CEAR'), ('CADCAN', 'CADCAN')], default='Seleccione...', max_length=50)),
                ('pais', models.CharField(choices=[('Cuba', 'Cuba'), ('Otro', 'Otro')], default='Seleccione...', max_length=50)),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50)),
                ('autores', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Autores')),
            ],
        ),
        migrations.CreateModel(
            name='PubliSeriada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issn', models.CharField(max_length=9)),
                ('doi', models.CharField(max_length=9)),
                ('fecha_creacion', models.DateField()),
                ('categoriaCientifica', models.CharField(choices=[('Funcionando', 'Funcionando'), ('Roto', 'Roto'), ('Baja', 'Baja'), ('Definir', 'Definir')], default='Seleccione...', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('editorial', models.CharField(default='Editorial...', max_length=200)),
                ('facultad', models.CharField(choices=[('Facultad de Ciencias Sociales', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50)),
                ('departamento', models.CharField(choices=[('CECID', 'CECID'), ('CEGEDEL', 'CEGEDEL'), ('CENFOLAB', 'CENFOLAB'), ('AFITCOMB', 'AFITCOMB'), ('CEGO', 'CEGO'), ('CECE', 'CECE'), ('CEAR', 'CEAR'), ('CADCAN', 'CADCAN')], default='Seleccione...', max_length=50)),
                ('pais', models.CharField(choices=[('Cuba', 'Cuba'), ('Otro', 'Otro')], default='Seleccione...', max_length=50)),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50)),
                ('autores', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Autores')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proyecto', models.CharField(max_length=100, unique=True)),
                ('nombre_proyecto', models.CharField(max_length=255)),
                ('area_uho', models.CharField(choices=[('Facultad de Ciencias Sociales', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], max_length=100)),
                ('departamento', models.CharField(choices=[('CECID', 'CECID'), ('CEGEDEL', 'CEGEDEL'), ('CENFOLAB', 'CENFOLAB'), ('AFITCOMB', 'AFITCOMB'), ('CEGO', 'CEGO'), ('CECE', 'CECE'), ('CEAR', 'CEAR'), ('CADCAN', 'CADCAN')], max_length=100)),
                ('tipo_proyecto', models.CharField(choices=[('PAPN', 'Proyectos Asociados a Programas Nacionales'), ('PAPS', 'Proyectos Asociados a Programas Sectoriales'), ('PAPT', 'Proyectos Asociados a Programas Territoriales'), ('PNAP', 'Proyectos No Asociados a Programas')], max_length=4)),
                ('subtipo_proyecto', models.CharField(blank=True, choices=[('PI', 'Proyectos Institucionales'), ('PE', 'Proyectos Empresariales'), ('PNE', 'Proyectos con Entidades No Empresariales y de la Administración Pública'), ('PDL', 'Proyectos de Desarrollo Local'), ('PRCI', 'Proyectos en Relación con la Colaboración Internacional')], max_length=4, null=True)),
                ('entidades_participantes', models.TextField()),
                ('sector_estrategico', models.CharField(choices=[('Sector 1', 'Sector Estratégico 1'), ('Sector 2', 'Sector Estratégico 2')], max_length=100)),
                ('linea_investigacion', models.CharField(choices=[('Línea 1', 'Línea de Investigación 1')], max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('estado_proyecto', models.CharField(choices=[('Normal', 'Normal'), ('Atrasado', 'Atrasado'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado'), ('Prórroga', 'Prórroga')], max_length=10)),
                ('cantidad_participantes', models.IntegerField()),
                ('cantidad_participantes_uho', models.IntegerField()),
                ('cantidad_estudiantes', models.IntegerField()),
                ('cantidad_participantes_otras_entidades', models.IntegerField()),
                ('cantidad_colaboradores', models.IntegerField()),
                ('cantidad_colaboradores_uho', models.IntegerField()),
                ('cantidad_estudiantes_gce', models.IntegerField()),
                ('cantidad_colaboradores_otras_entidades', models.IntegerField()),
                ('cantidad_estudiantes_segundo_ano', models.IntegerField()),
                ('cantidad_cuadros_uho', models.IntegerField()),
                ('presupuesto_planificado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], max_length=10)),
                ('jefe_proyecto', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Jefe de Proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_programa', models.CharField(max_length=100, unique=True)),
                ('nombre_programa', models.CharField(max_length=255)),
                ('facultad', models.CharField(choices=[('Facultad de Ciencias Sociales', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], max_length=100)),
                ('departamento', models.CharField(choices=[('CECID', 'CECID'), ('CEGEDEL', 'CEGEDEL'), ('CENFOLAB', 'CENFOLAB'), ('AFITCOMB', 'AFITCOMB'), ('CEGO', 'CEGO'), ('CECE', 'CECE'), ('CEAR', 'CEAR'), ('CADCAN', 'CADCAN')], max_length=100)),
                ('tipo_programa', models.CharField(choices=[('PAPN', 'Proyectos Asociados a Programas Nacionales'), ('PAPS', 'Proyectos Asociados a Programas Sectoriales'), ('PAPT', 'Proyectos Asociados a Programas Territoriales'), ('PNAP', 'Proyectos No Asociados a Programas')], max_length=4)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado_programa', models.CharField(choices=[('Normal', 'Normal'), ('Atrasado', 'Atrasado'), ('Terminado', 'Terminado'), ('Cancelado', 'Cancelado'), ('Prórroga', 'Prórroga')], max_length=10)),
                ('presupuesto_asignado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('presupuesto_utilizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50)),
                ('director_programa', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Director de Pograma')),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('aprobado', models.CharField(max_length=50, null=True)),
                ('facultad', models.CharField(choices=[('Facultad de Ciencias Sociales', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50)),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Regional', 'Regional'), ('Internacional', 'Internacional')], default='Seleccione...', max_length=50)),
                ('caracter_premio', models.CharField(choices=[('', 'Ninguno...'), ('Forum Ciencia Tecnica}', 'Forum Ciencia Tecnica'), ('Forum Nacionales Estudiantiles', 'Forum Nacionales Estudiantiles'), ('Jornadas Cientificas Estudiantiles', 'Jornadas Cientificas Estudiantiles')], default='Seleccione...', max_length=50)),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50)),
                ('url', models.URLField(verbose_name='')),
                ('autores', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Premiados')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caracter', models.CharField(choices=[('', 'Seleccione...'), ('Congreso', 'Congreso'), ('Jornada', 'Jornada'), ('Foro', 'Foro'), ('Conferencia', 'Conferencia'), ('Panel', 'Panel'), ('Simposio', 'Simposio'), ('Mesab Redonda', 'Mesa Redonda'), ('Taller', 'Taller'), ('Seminario', 'Seminario'), ('Convencion', 'Converncion'), ('Encuentro', 'Encuentro')], default='Seleccione...', max_length=50)),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Regional', 'Regional'), ('Internacional', 'Internacional')], default='Seleccione...', max_length=50)),
                ('presencialidad', models.CharField(choices=[('', 'Seleccione...'), ('Presencial', 'Presencial'), ('Virtual', 'Virtual'), ('Mixto', 'Mixto')], default='Seleccione...', max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=10)),
                ('publicacion', models.URLField()),
                ('fecha', models.DateField()),
                ('facultad', models.CharField(choices=[('Facultad de Ciencias Sociales', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50)),
                ('certificado', models.FileField(upload_to='eventos/')),
                ('aprobacion', models.CharField(choices=[('Pendiente', 'Pendiente'), ('No Valido', 'No Valido'), ('Aprobado', 'Aprobado')], default='Pendiente', max_length=50)),
                ('autores', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Autores')),
            ],
        ),
    ]
