# Generated by Django 5.0.4 on 2024-07-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='facultad',
            field=models.CharField(choices=[('FCS', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='evento',
            name='isbn',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='evento',
            name='publicacion',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='investigador',
            name='facultad',
            field=models.CharField(choices=[('FCS', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='premio',
            name='facultad',
            field=models.CharField(choices=[('FCS', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='programa',
            name='facultad',
            field=models.CharField(choices=[('FCS', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='area_uho',
            field=models.CharField(choices=[('FCS', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publiseriada',
            name='categoriaCientifica',
            field=models.CharField(choices=[('Investigador Agregado', 'Investigador Agregado'), ('Investigador Auxiliar', 'Investigador Auxiliar'), ('Investigador Titular', 'Investigador Titular')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='publiseriada',
            name='facultad',
            field=models.CharField(choices=[('FCS', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='publiunica',
            name='categoriaCientifica',
            field=models.CharField(choices=[('Investigador Agregado', 'Investigador Agregado'), ('Investigador Auxiliar', 'Investigador Auxiliar'), ('Investigador Titular', 'Investigador Titular')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='publiunica',
            name='facultad',
            field=models.CharField(choices=[('FCS', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50),
        ),
    ]
