# Generated by Django 5.0.4 on 2024-06-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marcadores', '0002_alter_evento_aprobacion_alter_investigador_rol_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
    ]
