# Generated by Django 5.0.4 on 2024-06-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Marcadores', '0003_alter_evento_options_alter_proyecto_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publiseriada',
            name='fecha',
        ),
    ]
