# Generated by Django 5.0.4 on 2024-06-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcadores', '0004_remove_publiseriada_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='departamento',
            field=models.CharField(choices=[('CECID', 'CECID'), ('CEGEDEL', 'CEGEDEL'), ('CENFOLAB', 'CENFOLAB'), ('AFITCOMB', 'AFITCOMB'), ('CEGO', 'CEGO'), ('CECE', 'CECE'), ('CEAR', 'CEAR'), ('CADCAN', 'CADCAN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='departamento',
            field=models.CharField(choices=[('CECID', 'CECID'), ('CEGEDEL', 'CEGEDEL'), ('CENFOLAB', 'CENFOLAB'), ('AFITCOMB', 'AFITCOMB'), ('CEGO', 'CEGO'), ('CECE', 'CECE'), ('CEAR', 'CEAR'), ('CADCAN', 'CADCAN')], max_length=100),
        ),
        migrations.AlterField(
            model_name='publiseriada',
            name='departamento',
            field=models.CharField(choices=[('CECID', 'CECID'), ('CEGEDEL', 'CEGEDEL'), ('CENFOLAB', 'CENFOLAB'), ('AFITCOMB', 'AFITCOMB'), ('CEGO', 'CEGO'), ('CECE', 'CECE'), ('CEAR', 'CEAR'), ('CADCAN', 'CADCAN')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='publiunica',
            name='departamento',
            field=models.CharField(choices=[('CECID', 'CECID'), ('CEGEDEL', 'CEGEDEL'), ('CENFOLAB', 'CENFOLAB'), ('AFITCOMB', 'AFITCOMB'), ('CEGO', 'CEGO'), ('CECE', 'CECE'), ('CEAR', 'CEAR'), ('CADCAN', 'CADCAN')], default='Seleccione...', max_length=50),
        ),
        migrations.AlterField(
            model_name='publiunica',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
