# Generated by Django 5.0.4 on 2024-06-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcadores', '0006_alter_premio_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='facultad',
            field=models.CharField(choices=[('Facultad de Ciencias Sociales', 'Facultad de Ciencias Sociales'), ('Facultad de Matematica-Informatica', 'Facultad de Matematica-Informatica'), ('Facultad de Ingenieria', 'Facultad de Ingenieria')], default='Seleccione...', max_length=50),
        ),
    ]
