# Generated by Django 5.0.4 on 2024-06-29 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marcadores', '0007_evento_facultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='isbn',
            field=models.CharField(max_length=10),
        ),
    ]
